language: go

services:
        - mysql

install:
        - make test-setup
        - make deps
        - go version

script:
        - make
        - make test

go:
        - 1.7.x
        - 1.8.x
        - master
